`ifndef SWITCH_DEFS_SVH
`define SWITCH_DEFS_SVH

`define SWITCH_BASIC_NUM_PORTS 4
`define SWITCH_BASIC_DATA_W 512
`define SWITCH_BASIC_KEEP_W 64
`define SWITCH_BASIC_TUSER_W 128
`define SWITCH_BASIC_PORT_W 8
`define SWITCH_BASIC_PHY_PORT_MASK 8'h0F

`define SWITCH_TUSER_LEN_LSB 0
`define SWITCH_TUSER_SRC_LSB 16
`define SWITCH_TUSER_DST_LSB 24

`define SWITCH_PORT0_1HOT 8'h01
`define SWITCH_PORT1_1HOT 8'h02
`define SWITCH_PORT2_1HOT 8'h04
`define SWITCH_PORT3_1HOT 8'h08

`endif
