`ifndef COLLECTIVE_DEFS_VH
`define COLLECTIVE_DEFS_VH

`define COLLECTIVE_TYPE_NONE       3'd0
`define COLLECTIVE_TYPE_ALLREDUCE  3'd1
`define COLLECTIVE_TYPE_MOE_COMBINE 3'd2
`define COLLECTIVE_TYPE_MOE_DISPATCH 3'd3

`define COLLECTIVE_OP_NONE         4'd0
`define COLLECTIVE_OP_INIT         4'd1
`define COLLECTIVE_OP_DATA         4'd2
`define COLLECTIVE_OP_DISPATCH     4'd3
`define COLLECTIVE_OP_RESULT       4'd4

`endif
